leaderboard:
  tasks:
    - name: Task 1
      weight: 20
    - name: Task 2
      weight: 30
    - name: Task 3
      weight: 50

display_name_field: "name"
score_fields: ["task_1", "task_2", "task_3"]
