leaderboard:
  tasks:
    - name: Task 1
      weight: 20
    - name: Task 2
      weight: 30
    - name: Task 3
      weight: 50
    - name: Task 4
      weight: 50
    - name: Task 5
      weight: 50
    - name: Task 6
      weight: 50
    - name: Task 7
      weight: 50
    - name: Task 8
      weight: 50
    - name: Task 9
      weight: 50
    - name: Task 10
      weight: 50
