leaderboard:
  tasks:
    - name: task_1
      weight: 20
    - name: task_2
      weight: 30
    - name: task_3
      weight: 50

display_name_field: "name"
score_fields: ["task_1", "task_2", "task_3"]
